// Code generated by gowsdl DO NOT EDIT.

package myservice

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type FindReport struct {
	XMLName xml.Name `xml:"http://www.139130.net FindReport"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Batchid string `xml:"batchid,omitempty" json:"batchid,omitempty"`

	Mobile string `xml:"mobile,omitempty" json:"mobile,omitempty"`

	Pageindex int32 `xml:"pageindex,omitempty" json:"pageindex,omitempty"`

	Flag int32 `xml:"flag,omitempty" json:"flag,omitempty"`
}

type FindReportResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net FindReportResponse"`

	FindReportResult *ArrayOfMTReport `xml:"FindReportResult,omitempty" json:"FindReportResult,omitempty"`
}

type FindResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net FindResponse"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Batchid string `xml:"batchid,omitempty" json:"batchid,omitempty"`

	Mobile string `xml:"mobile,omitempty" json:"mobile,omitempty"`

	Pageindex int32 `xml:"pageindex,omitempty" json:"pageindex,omitempty"`

	Flag int32 `xml:"flag,omitempty" json:"flag,omitempty"`
}

type FindResponseResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net FindResponseResponse"`

	FindResponseResult *ArrayOfMTResponse `xml:"FindResponseResult,omitempty" json:"FindResponseResult,omitempty"`
}

type GetAccountInfo struct {
	XMLName xml.Name `xml:"http://www.139130.net GetAccountInfo"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`
}

type GetAccountInfoResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net GetAccountInfoResponse"`

	GetAccountInfoResult *AccountInfo `xml:"GetAccountInfoResult,omitempty" json:"GetAccountInfoResult,omitempty"`
}

type GetBusinessType struct {
	XMLName xml.Name `xml:"http://www.139130.net GetBusinessType"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`
}

type GetBusinessTypeResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net GetBusinessTypeResponse"`

	GetBusinessTypeResult *ArrayOfBusinessType `xml:"GetBusinessTypeResult,omitempty" json:"GetBusinessTypeResult,omitempty"`
}

type GetMOMessage struct {
	XMLName xml.Name `xml:"http://www.139130.net GetMOMessage"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Pagesize int32 `xml:"pagesize,omitempty" json:"pagesize,omitempty"`
}

type GetMOMessageResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net GetMOMessageResponse"`

	GetMOMessageResult *ArrayOfMOMsg `xml:"GetMOMessageResult,omitempty" json:"GetMOMessageResult,omitempty"`
}

type GetReport struct {
	XMLName xml.Name `xml:"http://www.139130.net GetReport"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	PageSize int32 `xml:"PageSize,omitempty" json:"PageSize,omitempty"`
}

type GetReportResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net GetReportResponse"`

	GetReportResult *ArrayOfMTReport `xml:"GetReportResult,omitempty" json:"GetReportResult,omitempty"`
}

type GetResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net GetResponse"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	PageSize int32 `xml:"PageSize,omitempty" json:"PageSize,omitempty"`
}

type GetResponseResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net GetResponseResponse"`

	GetResponseResult *ArrayOfMTResponse `xml:"GetResponseResult,omitempty" json:"GetResponseResult,omitempty"`
}

type ModifyPassword struct {
	XMLName xml.Name `xml:"http://www.139130.net ModifyPassword"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Old_password string `xml:"old_password,omitempty" json:"old_password,omitempty"`

	New_password string `xml:"new_password,omitempty" json:"new_password,omitempty"`
}

type ModifyPasswordResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net ModifyPasswordResponse"`

	ModifyPasswordResult int32 `xml:"ModifyPasswordResult,omitempty" json:"ModifyPasswordResult,omitempty"`
}

type Post struct {
	XMLName xml.Name `xml:"http://www.139130.net Post"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Mtpack *MTPacks `xml:"mtpack,omitempty" json:"mtpack,omitempty"`
}

type PostGroup struct {
	XMLName xml.Name `xml:"http://www.139130.net PostGroup"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Mssages *ArrayOfMessageData `xml:"mssages,omitempty" json:"mssages,omitempty"`

	Subid string `xml:"subid,omitempty" json:"subid,omitempty"`
}

type PostGroupResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net PostGroupResponse"`

	PostGroupResult int32 `xml:"PostGroupResult,omitempty" json:"PostGroupResult,omitempty"`
}

type PostMass struct {
	XMLName xml.Name `xml:"http://www.139130.net PostMass"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Mobiles *ArrayOfString `xml:"mobiles,omitempty" json:"mobiles,omitempty"`

	Content string `xml:"content,omitempty" json:"content,omitempty"`

	Subid string `xml:"subid,omitempty" json:"subid,omitempty"`
}

type PostMassResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net PostMassResponse"`

	PostMassResult int32 `xml:"PostMassResult,omitempty" json:"PostMassResult,omitempty"`
}

type PostResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net PostResponse"`

	PostResult *GsmsResponse `xml:"PostResult,omitempty" json:"PostResult,omitempty"`
}

type PostSingle struct {
	XMLName xml.Name `xml:"http://www.139130.net PostSingle"`

	Account string `xml:"account,omitempty" json:"account,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Mobile string `xml:"mobile,omitempty" json:"mobile,omitempty"`

	Content string `xml:"content,omitempty" json:"content,omitempty"`

	Subid string `xml:"subid,omitempty" json:"subid,omitempty"`
}

type PostSingleResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net PostSingleResponse"`

	PostSingleResult int32 `xml:"PostSingleResult,omitempty" json:"PostSingleResult,omitempty"`
}

type SetMedias struct {
	XMLName xml.Name `xml:"http://www.139130.net SetMedias"`

	FullPath string `xml:"fullPath,omitempty" json:"fullPath,omitempty"`
}

type SetMediasResponse struct {
	XMLName xml.Name `xml:"http://www.139130.net SetMediasResponse"`

	SetMediasResult *ArrayOfMediaItems `xml:"SetMediasResult,omitempty" json:"SetMediasResult,omitempty"`
}

type ArrayOfString struct {
	Astring []string `xml:"string,omitempty" json:"string,omitempty"`
}

type ArrayOfMOMsg struct {
	MOMsg []*MOMsg `xml:"MOMsg,omitempty" json:"MOMsg,omitempty"`
}

type MOMsg struct {
	Phone string `xml:"Phone,omitempty" json:"Phone,omitempty"`

	Content string `xml:"Content,omitempty" json:"Content,omitempty"`

	MsgType int32 `xml:"MsgType,omitempty" json:"MsgType,omitempty"`

	SpecNumber string `xml:"SpecNumber,omitempty" json:"SpecNumber,omitempty"`

	ServiceType string `xml:"ServiceType,omitempty" json:"ServiceType,omitempty"`

	ReceiveTime time.Time `xml:"ReceiveTime,omitempty" json:"ReceiveTime,omitempty"`

	Reserve string `xml:"Reserve,omitempty" json:"Reserve,omitempty"`
}

type ArrayOfMTResponse struct {
	MTResponse []*MTResponse `xml:"MTResponse,omitempty" json:"MTResponse,omitempty"`
}

type MTResponse struct {
	BatchID string `xml:"batchID,omitempty" json:"batchID,omitempty"`

	MsgID string `xml:"msgID,omitempty" json:"msgID,omitempty"`

	CustomMsgID string `xml:"customMsgID,omitempty" json:"customMsgID,omitempty"`

	State int32 `xml:"state,omitempty" json:"state,omitempty"`

	Phone string `xml:"phone,omitempty" json:"phone,omitempty"`

	Total int32 `xml:"total,omitempty" json:"total,omitempty"`

	Number int32 `xml:"number,omitempty" json:"number,omitempty"`

	SubmitRespTime time.Time `xml:"submitRespTime,omitempty" json:"submitRespTime,omitempty"`

	OriginResult string `xml:"originResult,omitempty" json:"originResult,omitempty"`

	Reserve string `xml:"reserve,omitempty" json:"reserve,omitempty"`

	Id int64 `xml:"id,omitempty" json:"id,omitempty"`
}

type ArrayOfMTReport struct {
	MTReport []*MTReport `xml:"MTReport,omitempty" json:"MTReport,omitempty"`
}

type MTReport struct {
	Id int64 `xml:"id,omitempty" json:"id,omitempty"`

	BatchID string `xml:"batchID,omitempty" json:"batchID,omitempty"`

	Phone string `xml:"phone,omitempty" json:"phone,omitempty"`

	MsgID string `xml:"msgID,omitempty" json:"msgID,omitempty"`

	CustomMsgID string `xml:"customMsgID,omitempty" json:"customMsgID,omitempty"`

	State int32 `xml:"state,omitempty" json:"state,omitempty"`

	Total int32 `xml:"total,omitempty" json:"total,omitempty"`

	Number int32 `xml:"number,omitempty" json:"number,omitempty"`

	SubmitTime time.Time `xml:"submitTime,omitempty" json:"submitTime,omitempty"`

	DoneTime time.Time `xml:"doneTime,omitempty" json:"doneTime,omitempty"`

	OriginResult string `xml:"originResult,omitempty" json:"originResult,omitempty"`

	Reserve string `xml:"reserve,omitempty" json:"reserve,omitempty"`
}

type AccountInfo struct {
	Account string `xml:"Account,omitempty" json:"Account,omitempty"`

	Name string `xml:"Name,omitempty" json:"Name,omitempty"`

	Identify string `xml:"Identify,omitempty" json:"Identify,omitempty"`

	BizNames *ArrayOfString `xml:"BizNames,omitempty" json:"BizNames,omitempty"`

	Userbrief string `xml:"Userbrief,omitempty" json:"Userbrief,omitempty"`

	Balance float64 `xml:"Balance,omitempty" json:"Balance,omitempty"`

	Reserve string `xml:"Reserve,omitempty" json:"Reserve,omitempty"`
}

type MTPacks struct {
	Uuid string `xml:"uuid,omitempty" json:"uuid,omitempty"`

	BatchID string `xml:"batchID,omitempty" json:"batchID,omitempty"`

	BatchName string `xml:"batchName,omitempty" json:"batchName,omitempty"`

	SendType int32 `xml:"sendType,omitempty" json:"sendType,omitempty"`

	MsgType int32 `xml:"msgType,omitempty" json:"msgType,omitempty"`

	Medias *ArrayOfMediaItems `xml:"medias,omitempty" json:"medias,omitempty"`

	Msgs *ArrayOfMessageData `xml:"msgs,omitempty" json:"msgs,omitempty"`

	BizType int32 `xml:"bizType,omitempty" json:"bizType,omitempty"`

	DistinctFlag bool `xml:"distinctFlag,omitempty" json:"distinctFlag,omitempty"`

	ScheduleTime int64 `xml:"scheduleTime,omitempty" json:"scheduleTime,omitempty"`

	Remark string `xml:"remark,omitempty" json:"remark,omitempty"`

	CustomNum string `xml:"customNum,omitempty" json:"customNum,omitempty"`

	Deadline int64 `xml:"deadline,omitempty" json:"deadline,omitempty"`

	TemplateNo string `xml:"templateNo,omitempty" json:"templateNo,omitempty"`
}

type ArrayOfMediaItems struct {
	MediaItems []*MediaItems `xml:"MediaItems,omitempty" json:"MediaItems,omitempty"`
}

type MediaItems struct {
	Meta string `xml:"meta,omitempty" json:"meta,omitempty"`

	Data []byte `xml:"data,omitempty" json:"data,omitempty"`
}

type ArrayOfMessageData struct {
	MessageData []*MessageData `xml:"MessageData,omitempty" json:"MessageData,omitempty"`
}

type MessageData struct {
	Phone string `xml:"Phone,omitempty" json:"Phone,omitempty"`

	Content string `xml:"Content,omitempty" json:"Content,omitempty"`

	VipFlag bool `xml:"vipFlag,omitempty" json:"vipFlag,omitempty"`

	CustomMsgID string `xml:"customMsgID,omitempty" json:"customMsgID,omitempty"`

	Medias *ArrayOfMediaItems `xml:"medias,omitempty" json:"medias,omitempty"`
}

type GsmsResponse struct {
	Result int32 `xml:"result,omitempty" json:"result,omitempty"`

	Uuid string `xml:"uuid,omitempty" json:"uuid,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`

	Attributes string `xml:"attributes,omitempty" json:"attributes,omitempty"`
}

type ArrayOfBusinessType struct {
	BusinessType []*BusinessType `xml:"BusinessType,omitempty" json:"BusinessType,omitempty"`
}

type BusinessType struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Name string `xml:"Name,omitempty" json:"Name,omitempty"`

	Priority int32 `xml:"Priority,omitempty" json:"Priority,omitempty"`

	StartTime string `xml:"StartTime,omitempty" json:"StartTime,omitempty"`

	EndTime string `xml:"EndTime,omitempty" json:"EndTime,omitempty"`

	ExtendFlag bool `xml:"ExtendFlag,omitempty" json:"ExtendFlag,omitempty"`

	State int32 `xml:"state,omitempty" json:"state,omitempty"`

	BindChs *ArrayOfBindChannel `xml:"bindChs,omitempty" json:"bindChs,omitempty"`
}

type ArrayOfBindChannel struct {
	BindChannel []*BindChannel `xml:"BindChannel,omitempty" json:"BindChannel,omitempty"`
}

type BindChannel struct {
	ChannelNum string `xml:"ChannelNum,omitempty" json:"ChannelNum,omitempty"`

	Carrier string `xml:"Carrier,omitempty" json:"Carrier,omitempty"`

	SendType string `xml:"SendType,omitempty" json:"SendType,omitempty"`
}

type WebServiceSoap interface {
	GetBusinessType(request *GetBusinessType) (*GetBusinessTypeResponse, error)

	GetBusinessTypeContext(ctx context.Context, request *GetBusinessType) (*GetBusinessTypeResponse, error)

	GetAccountInfo(request *GetAccountInfo) (*GetAccountInfoResponse, error)

	GetAccountInfoContext(ctx context.Context, request *GetAccountInfo) (*GetAccountInfoResponse, error)

	ModifyPassword(request *ModifyPassword) (*ModifyPasswordResponse, error)

	ModifyPasswordContext(ctx context.Context, request *ModifyPassword) (*ModifyPasswordResponse, error)

	Post(request *Post) (*PostResponse, error)

	PostContext(ctx context.Context, request *Post) (*PostResponse, error)

	PostSingle(request *PostSingle) (*PostSingleResponse, error)

	PostSingleContext(ctx context.Context, request *PostSingle) (*PostSingleResponse, error)

	GetMOMessage(request *GetMOMessage) (*GetMOMessageResponse, error)

	GetMOMessageContext(ctx context.Context, request *GetMOMessage) (*GetMOMessageResponse, error)

	PostMass(request *PostMass) (*PostMassResponse, error)

	PostMassContext(ctx context.Context, request *PostMass) (*PostMassResponse, error)

	PostGroup(request *PostGroup) (*PostGroupResponse, error)

	PostGroupContext(ctx context.Context, request *PostGroup) (*PostGroupResponse, error)

	GetResponse(request *GetResponse) (*GetResponseResponse, error)

	GetResponseContext(ctx context.Context, request *GetResponse) (*GetResponseResponse, error)

	GetReport(request *GetReport) (*GetReportResponse, error)

	GetReportContext(ctx context.Context, request *GetReport) (*GetReportResponse, error)

	FindResponse(request *FindResponse) (*FindResponseResponse, error)

	FindResponseContext(ctx context.Context, request *FindResponse) (*FindResponseResponse, error)

	FindReport(request *FindReport) (*FindReportResponse, error)

	FindReportContext(ctx context.Context, request *FindReport) (*FindReportResponse, error)

	SetMedias(request *SetMedias) (*SetMediasResponse, error)

	SetMediasContext(ctx context.Context, request *SetMedias) (*SetMediasResponse, error)
}

type webServiceSoap struct {
	client *soap.Client
}

func NewWebServiceSoap(client *soap.Client) WebServiceSoap {
	return &webServiceSoap{
		client: client,
	}
}

func (service *webServiceSoap) GetBusinessTypeContext(ctx context.Context, request *GetBusinessType) (*GetBusinessTypeResponse, error) {
	response := new(GetBusinessTypeResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/GetBusinessType", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) GetBusinessType(request *GetBusinessType) (*GetBusinessTypeResponse, error) {
	return service.GetBusinessTypeContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) GetAccountInfoContext(ctx context.Context, request *GetAccountInfo) (*GetAccountInfoResponse, error) {
	response := new(GetAccountInfoResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/GetAccountInfo", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) GetAccountInfo(request *GetAccountInfo) (*GetAccountInfoResponse, error) {
	return service.GetAccountInfoContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) ModifyPasswordContext(ctx context.Context, request *ModifyPassword) (*ModifyPasswordResponse, error) {
	response := new(ModifyPasswordResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/ModifyPassword", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) ModifyPassword(request *ModifyPassword) (*ModifyPasswordResponse, error) {
	return service.ModifyPasswordContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) PostContext(ctx context.Context, request *Post) (*PostResponse, error) {
	response := new(PostResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/Post", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) Post(request *Post) (*PostResponse, error) {
	return service.PostContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) PostSingleContext(ctx context.Context, request *PostSingle) (*PostSingleResponse, error) {
	response := new(PostSingleResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/PostSingle", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) PostSingle(request *PostSingle) (*PostSingleResponse, error) {
	return service.PostSingleContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) GetMOMessageContext(ctx context.Context, request *GetMOMessage) (*GetMOMessageResponse, error) {
	response := new(GetMOMessageResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/GetMOMessage", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) GetMOMessage(request *GetMOMessage) (*GetMOMessageResponse, error) {
	return service.GetMOMessageContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) PostMassContext(ctx context.Context, request *PostMass) (*PostMassResponse, error) {
	response := new(PostMassResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/PostMass", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) PostMass(request *PostMass) (*PostMassResponse, error) {
	return service.PostMassContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) PostGroupContext(ctx context.Context, request *PostGroup) (*PostGroupResponse, error) {
	response := new(PostGroupResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/PostGroup", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) PostGroup(request *PostGroup) (*PostGroupResponse, error) {
	return service.PostGroupContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) GetResponseContext(ctx context.Context, request *GetResponse) (*GetResponseResponse, error) {
	response := new(GetResponseResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/GetResponse", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) GetResponse(request *GetResponse) (*GetResponseResponse, error) {
	return service.GetResponseContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) GetReportContext(ctx context.Context, request *GetReport) (*GetReportResponse, error) {
	response := new(GetReportResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/GetReport", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) GetReport(request *GetReport) (*GetReportResponse, error) {
	return service.GetReportContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) FindResponseContext(ctx context.Context, request *FindResponse) (*FindResponseResponse, error) {
	response := new(FindResponseResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/FindResponse", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) FindResponse(request *FindResponse) (*FindResponseResponse, error) {
	return service.FindResponseContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) FindReportContext(ctx context.Context, request *FindReport) (*FindReportResponse, error) {
	response := new(FindReportResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/FindReport", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) FindReport(request *FindReport) (*FindReportResponse, error) {
	return service.FindReportContext(
		context.Background(),
		request,
	)
}

func (service *webServiceSoap) SetMediasContext(ctx context.Context, request *SetMedias) (*SetMediasResponse, error) {
	response := new(SetMediasResponse)
	err := service.client.CallContext(ctx, "http://www.139130.net/SetMedias", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *webServiceSoap) SetMedias(request *SetMedias) (*SetMediasResponse, error) {
	return service.SetMediasContext(
		context.Background(),
		request,
	)
}
